/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Monitor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_2.geometry}
        material={materials.metalDark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_2_1.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_3.geometry}
        material={materials.metal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.computerScreen_3_1.geometry}
        material={materials.metalDark}
      />
    </group>
  )
}

useGLTF.preload('/Monitor.glb')
